/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;
import edu.princeton.cs.algs4.Draw;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello World");

        Draw a = new Draw();
        a.text(0.5,0.5,"Hello World");
    }
}
