/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int input = -1;

        int totalMoedas01 = 0;
        int totalMoedas05 = 0;
        int totalMoedas10 = 0;
        int totalMoedas25 = 0;
        int totalMoedas50 = 0;
        int totalMoedas100 = 0;

        while (input != 0) {
            System.out.println("Sua moeda é de quantos centavos? (0 pra sair)");
            input = scanner.nextInt();
            scanner.nextLine();


            switch (input) {
                case 1:
                    totalMoedas01++;
                    break;
                case 5:
                    totalMoedas05++;
                    break;
                case 10:
                    totalMoedas10++;
                    break;
                case 25:
                    totalMoedas25++;
                    break;
                case 50:
                    totalMoedas50++;
                    break;
                case 100:
                    totalMoedas100++;
                    break;

                default:
                    if (input != 0) {
                        System.out.println("Moeda inválida");
                    }
                   break;
            }
            
        }
        System.out.println("Total de moedas de 1 centavo: " + totalMoedas01);
        System.out.println("Total de moedas de 5 centavos: " + totalMoedas05);
        System.out.println("Total de moedas de 10 centavos: " + totalMoedas10);
        System.out.println("Total de moedas de 25 centavos: " + totalMoedas25);
        System.out.println("Total de moedas de 50 centavos: " + totalMoedas50);
        System.out.println("Total de moedas de 1 real: " + totalMoedas100);

        double totalReais = totalMoedas01 + totalMoedas05 * 5 + totalMoedas10 * 10 + totalMoedas25 * 25 + totalMoedas50 * 50 + totalMoedas100 * 100;

        System.out.println("Total em reais: " + totalReais / 100);
        
        
        scanner.close();

    }
}
