/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner teclado = new Scanner(System.in);
       
        while (teclado.hasNext()) {
            String linha = teclado.next();
            System.out.println(linha.toUpperCase());
        }

        teclado.close();
    }
}
