/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {

        Estudante a = new Estudante("deyverson", 8, 2);
        System.out.println(a.toString());
        System.out.println(Estudante.getTotalEstudantes());

    }
}
