/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {

        // Carro fusca = new Carro();
        // Carro gol = new Carro();

        // fusca.definirVelocidade(10);
        // gol.definirVelocidade(30);

        // fusca.definirCor("azul");
        // gol.definirCor("verde");

        // fusca.definirModelo("Fusca");
        // gol.definirModelo("Gol");

        // fusca.listarAtributos();
        // gol.listarAtributos();

        Caneta bic = new Caneta();
        bic.definirCor("azul");

        System.out.println(bic.desenhar(10));
    }
}
